services:
  - type: web
    name: workpro-site
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    customDomains:
      - name: workpro.kr
      - name: www.workpro.kr
